import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const inter = Barlow({ weight: ["100", "400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen px-4 desktop:px-10`}>
        <Navbar />
        <main className="flex flex-col min-h-screen-minus-nav items-center justify-between mt-10">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
